# This is a basic workflow to help you get started with Actions

name: clear All Results

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Run script file
      run: |
         @echo "Clearing all results"
         find . -name "*_results.txt" -print -delete
       
