# This is a basic workflow to help you get started with Actions

name: clear All Results

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ClearingAllResultFiles:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clearing all results
      run: |         
         find . -name "*_results.txt" -print -delete
         find . -name "results_summary.json" -print -delete;
         find . -name "*-error.log" -print -delete
         find . -name "*-result.json" -print -delete 
         find . -name "*_results.txt" -print -delete 
         find . -name "*_report.html" -print -delete 
         find . -name "*-logs.txt" -print -delete 
    - name: Commit files
      run: |
            git config --local user.email "lambay.salil@gmail.com"
            git config --local user.name "Salil"
            git add .
            git commit -m "Report Added" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: ${{ github.ref }}
       
