# This is a basic workflow to help you get started with Actions

name: Scan

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x run_all_tools.sh
         ./run_all_tools.sh
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       CLOUDRAIL_API_KEY: ${{ secrets.CLOUDRAIL_API_KEY }}
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      shell: bash
      
    - name: Install Python
      uses: actions/setup-python@v2 
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        
    - name: Run Py to update the ReadMe    
      run: python generate_readme_tables.py > README.md
      
    - name: Commit files
      run: |
            git config --local user.email "lambay.salil@gmail.com"
            git config --local user.name "Salil"
            git add .
            git commit -m "Report Added" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: ${{ github.ref }}
